# Set <C-Space> as prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-pane -L
bind -r C-j select-pane -D
bind -r C-k select-pane -U
bind -r C-l select-pane -R
bind M swap-pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r C-S-h {
    swap-pane -t '{left-of}'
    select-pane -t '{left-of}'
}
bind -r C-S-j {
    swap-pane -t '{down-of}'
    select-pane -t '{down-of}'
}
bind -r C-S-k {
    swap-pane -t '{up-of}'
    select-pane -t '{up-of}'
}
bind -r C-S-l {
    swap-pane -t '{right-of}'
    select-pane -t '{right-of}'
}
bind \" split-window -v -c "#{pane_current_path}"
bind \% split-window -h -c "#{pane_current_path}"

bind -r Space next-layout
bind c new-window -c "#{pane_current_path}"
bind S set -w synchronize-panes
bind C-w popup -E -h 3 -w 30% -T "New window name" "sh -c 'read new_name && tmux rename-window \$new_name'"
bind -r C-p {
    swap-window -t '{previous}'
    select-window -t '{previous}'
}
bind -r C-n {
    swap-window -t '{next}'
    select-window -t '{next}'
}

bind u switch-client -p
bind i switch-client -n
bind s new-session
bind C-s popup -E -h 3 -w 30% -T "New session name" "sh -c 'read new_name && tmux rename-session \$new_name'"
bind q {
    confirm-before -p "kill-session #S? (y/n)" {
        run-shell "tmux switch-client -p; tmux kill-session -t #S"
    }
}

bind r {
    display "Reloading..."
    source "$HOME/.tmux.conf"
    display "Done"
}

set -wg mode-keys vi
set -g allow-passthrough on
set -g escape-time 10 # Fix https://github.com/microsoft/WSL/issues/5931
set -g mouse on
set -g repeat-time 10000
set -g set-clipboard on

# Enable TrueColor support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Color scheme
source "$DOTPATH/configs/tmux/blue.tmux"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# Initialize TPM
if-shell "test -d '$HOME/.tmux/plugins/tpm'" {
    run-shell "$HOME/.tmux/plugins/tpm/tpm"
}
