[general]
import = [
    "~/.config/dotfiles/local/alacritty/alacritty.toml",
    "~/.config/alacritty/tokyonight_night.toml",
]

[[keyboard.bindings]]
key = ";"
mods = "Control"
action = "IncreaseFontSize"

[window]
opacity = 0.7
blur = true
