#!/bin/sh -eu

export_and_mkdir() {
	if [ $# -ne 2 ]; then
		abort "export_and_mkdir requires exactly 2 arguments"
	fi

	export "$1"="$2"
	mkdir -p "$2"
}

bootstrap() {
	if ! DOTPATH="$(cd "$(dirname "$0")" && pwd)"; then
		echo "Failed to resolve DOTPATH" >&2
	fi
	export DOTPATH
	echo "${DOTPATH}" >"${HOME}/.dotpath"

	. "${DOTPATH}/scripts/lib/log.sh"
	. "${DOTPATH}/scripts/lib/migration.sh"

	export_and_mkdir XDG_CONFIG_HOME "${HOME}/.config"
	export_and_mkdir XDG_DATA_HOME "${HOME}/.local/share"
	export_and_mkdir DOTFILES_CONFIG_HOME "${DOTPATH}/configs"
	export_and_mkdir DOTFILES_DATA_HOME "${XDG_DATA_HOME}/dotfiles"
	export_and_mkdir DOTFILES_LOCAL_HOME "${XDG_CONFIG_HOME}/dotfiles//local"
	export_and_mkdir DOTFILES_ORIGINAL_HOME "${XDG_CONFIG_HOME}/dotfiles/original"
}

execute_script() {
	if [ $# -eq 0 ]; then
		echo "Usage: $0 <subcommand> [args...]"
		abort "Subcommand is required."
	fi

	local subcommand="$1"
	shift

	local subcommand_source="${DOTPATH}/scripts/${subcommand}.sh"
	if [ -x "${subcommand_source}" ]; then
		"${subcommand_source}" "$@"
	else
		abort "Unknown subcommand: ${subcommand}"
	fi
}

main() {
	bootstrap
	execute_script "$@"
}

main "$@"
