#!/bin/sh

export_and_mkdir() {
	if [ $# -ne 2 ]; then
		abort "export_and_mkdir requires exactly 2 arguments"
	fi

	export "$1"="$2"
	mkdir -p "$2"
}

bootstrap() {
	if ! DOTPATH="$(cd "$(dirname "$0")" && pwd)"; then
		echo "Failed to resolve DOTPATH" >&2
	fi
	export DOTPATH
	echo "${DOTPATH}" >"${HOME}/.dotpath"

	. "${DOTPATH}/scripts/lib/log.sh"

	export_and_mkdir XDG_CONFIG_HOME "${HOME}/.config"
	export_and_mkdir DOTFILES_CONFIG_HOME "${XDG_CONFIG_HOME}/dotfiles"
	export_and_mkdir DOTFILES_LOCAL_HOME "${DOTFILES_CONFIG_HOME}/local"
	export_and_mkdir DOTFILES_ORIGINAL_HOME "${DOTFILES_CONFIG_HOME}/original"
}

execute_script() {
	subcommand="$1"

	if [ -z "${subcommand}" ]; then
		echo "Usage: $0 <subcommand> [args...]"
		abort "Subcommand is required."
	fi
	shift

	subcommand_source="${DOTPATH}/scripts/${subcommand}.sh"
	if [ -r "${subcommand_source}" ]; then
		"${subcommand_source}" "$@"
	else
		abort "Unknown subcommand: ${subcommand}"
	fi
}

main() {
	bootstrap
	execute_script "$@"
}

main "$@"
