format = """
 \
$shlvl\
$username\
$hostname\
$directory\
[](blue)\
$git_branch\
$git_status\
$git_state\
[](blue)\
$aws\
$c\
$docker_context\
$golang\
$haskell\
$lua\
$nodejs\
$package\
$python\
$ruby\
$rust\
\n$character"""

[hostname]
ssh_symbol = " "
format = '[$ssh_symbol$hostname ](bold dimmed blue)'

[directory]
read_only = " 󰌾"
style = 'blue'
repo_root_style = 'bold blue'
before_repo_root_style = 'blue'
truncation_length = 0
format = '[ $path$read_only ](blue)'

[git_branch]
symbol = ""
format = '[ $symbol $branch](fg:blue)'

[git_status]
format = '[ $all_status$ahead_behind](fg:blue)'

[git_state]
format = '[ $state ($progress_current/$progress_total)](blue)'

[aws]
symbol = "  "
format = '[ $symbol ](blue)'

[c]
symbol = " "
format = '[ $symbol ](blue)'

[docker_context]
symbol = " "
format = '[ $symbol ](blue)'

[golang]
symbol = " "
format = '[ $symbol ](blue)'

[haskell]
symbol = " "
format = '[ $symbol ](blue)'

[lua]
symbol = " "
format = '[ $symbol ](blue)'

[nodejs]
symbol = " "
format = '[ $symbol ](blue)'

[package]
symbol = "󰏗 "
format = '[ $symbol ](blue)'

[python]
symbol = " "
format = '[ $symbol ](blue)'

[ruby]
symbol = " "
format = '[ $symbol ](blue)'

[rust]
symbol = " "
format = '[ $symbol ](blue)'
