require("keke.setup_noplugin.colorscheme")
require("keke.setup_noplugin.completion")
require("keke.setup_noplugin.fzf")
require("keke.setup_noplugin.jump")
require("keke.setup_noplugin.lsp")
require("keke.setup_noplugin.netrw")
require("keke.setup_noplugin.session")
