[gen]
model = "dall-e-3"
quality = "hd"
size = "1792x1024"
prompt = "A sky blends with a night over a mirror-like lakeside landscape. The lake surface reflects the lights perfectly, silhouetted the lights of distant town. The sky showcases a pale centered gradient of pink, orange, purple, and blue fron the center, dotted dramatically with clouds. The style is soft anime-like with a sense of realism."
