---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
    - all
registries:
  - type: standard
    ref: v4.246.1 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: tfutils/tfenv@v3.0.0
  - name: ogham/exa@v0.10.1
  - name: sharkdp/bat@v0.24.0
  - name: neovim/neovim@v0.10.2
  - name: starship/starship@v1.21.1
  - name: junegunn/fzf@v0.56.0
  - name: BurntSushi/ripgrep@14.1.1
  - name: direnv/direnv@v2.35.0
  - name: ajeetdsouza/zoxide@v0.9.6
  - name: aws/aws-cli@2.19.4
  - name: kubernetes/kubectl@v1.31.2
  - name: ahmetb/kubectx@v0.9.5
  - name: stern/stern@v1.31.0
