---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
    - all
registries:
  - type: standard
    ref: v4.393.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: tfutils/tfenv@v3.0.0
  - name: ogham/exa@v0.10.1
  - name: sharkdp/bat@v0.25.0
  - name: neovim/neovim@v0.11.3
  - name: starship/starship@v1.23.0
  - name: junegunn/fzf@v0.64.0
  - name: BurntSushi/ripgrep@14.1.1
  - name: direnv/direnv@v2.37.1
  - name: ajeetdsouza/zoxide@v0.9.8
  - name: aws/aws-cli@2.27.60
  - name: kubernetes/kubectl@v1.33.3
  - name: ahmetb/kubectx@v0.9.5
  - name: stern/stern@v1.32.0
  - name: nektos/act@v0.2.79
  - name: astral-sh/uv@0.8.3
  - name: oberblastmeister/trashy@v2.0.0
  - name: sharkdp/fd@v10.2.0
  - name: dandavison/delta@0.18.2
  - name: dalance/procs@v0.14.10
  - name: nushell/nushell@0.106.0
  - name: zellij-org/zellij@v0.42.2
  - name: astral-sh/uv@0.8.3
