[project]
name = "karabiner"
version = "0.1.0"
description = "Generate Karabiner-Elements configuration file"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = ["black>=24.10.0", "mypy>=1.13.0"]

[tool.black]
line-length = 120
