onboarding = false
[theme]
name = "tokyo-night"

[keys]
prefix = "ctrl+space"
help = "prefix+?"
reload_config = "prefix+shift+r"
detach = "prefix+d"
copy_mode = "prefix+["
goto = "prefix+g"

new_workspace = "prefix+s"
close_workspace = "prefix+q"
rename_workspace = "prefix+ctrl+w"
previous_workspace = "prefix+o"
next_workspace = "prefix+i"

previous_agent = "prefix+ctrl+o"
next_agent = "prefix+tab" # equivalent to prefix+ctrl+i

new_tab = "prefix+c"
rename_tab = "prefix+ctrl+r"
previous_tab = "prefix+p"
next_tab = "prefix+n"

split_vertical = "prefix+percent"
split_horizontal = "prefix+\""
close_pane = "prefix+x"
focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"
resize_mode = "prefix+r"
navigate_pane_left = "h"
navigate_pane_down = "j"
navigate_pane_up = "k"
navigate_pane_right = "l"
swap_pane_left = "prefix+ctrl+h"
swap_pane_down = "prefix+ctrl+j"
swap_pane_up = "prefix+ctrl+k"
swap_pane_right = "prefix+ctrl+l"

[ui]
pane_gaps = false
agent_panel_sort = "spaces"

[ui.toast]
delivery = "herdr"
