name: "installation test"

on: push

jobs:
  installation-test:
    strategy:
      matrix:
        container:
          - ubuntu:latest
          - debian:latest
          - archlinux:latest
          - alpine:latest
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4

      - name: Print shell
        run: realpath /bin/sh

      - name: Run installation
        run: ./dot install
