name: "installation test"

on: push

jobs:
  installation-test:
    strategy:
      matrix:
        container:
          - ubuntu:latest
          - debian:latest
          - archlinux:latest
          - alpine:latest
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Print shell
        run: realpath /bin/sh

      - name: Run migration
        run: yes | ./dot migrate

      - name: Run installation
        run: ./dot install

      - name: Run restoration
        run: ./dot restore

  run-initialize-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Run migration
        run: yes | ./dot migrate

      - name: Run installation
        run: ./dot install

      - name: Run initialize script
        run: nix develop '#initialize-test' -c ./dot init

  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Bats
        uses: bats-core/bats-action@472edde1138d59aca53ff162fb8d996666d21e4a # 2.0.0

      - name: Run migration
        run: yes | ./dot migrate

      - name: Run tests
        run: ./dot test
