name: "installation test"

on: push

jobs:
  installation-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh


  set-unit-installation-script-matrix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - working-directory: configs
        id: set-matrix
        run: |
          scripts=$(dir -1 | xargs -I {} echo \"./{}/install.sh\" | paste -s -d ',')
          echo "::set-output name=script-matrix::[ ${scripts} ]"

    outputs:
      installation-script-matrix: ${{ steps.set-matrix.outputs.script-matrix }}


  unit-installation-test:
    needs: set-unit-installation-script-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        script: ${{ fromJSON(needs.set-unit-installation-script-matrix.outputs.installation-script-matrix) }}

    steps:
      - uses: actions/checkout@v2
      - working-directory: configs
        run: ${{ matrix.script }}
