name: "installation test"

on: push

jobs:
  installation-test:
    strategy:
      matrix:
        container:
          - ubuntu:latest
          - debian:latest
          - archlinux:latest
          - alpine:latest
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4

      - name: Print shell
        run: realpath /bin/sh

      - name: Run migration
        run: yes | ./dot migrate

      - name: Run installation
        run: ./dot install

      - name: Run restoration
        run: ./dot restore

  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bats
        uses: bats-core/bats-action@2.0.0

      - name: Run migration
        run: yes | ./dot migrate

      - name: Run tests
        run: ./dot test
